### ISSUE TITLE
Sttp client failing with Java 8

### ISSUE THREAD

**Issue by Andrapyre** [lumidion/sonatype-central-client#11]
## Description

When the sttp client runs with Java 8, it produces the following error in [Github Actions](https://github.com/lumidion/sonatype-central-client/actions/runs/11962764958/job/33351848551#step:9:29) on all Scala versions:

```
java.lang.UnsupportedClassVersionError: sttp/client4/httpurlconnection/HttpURLConnectionBackend$ has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

First raised in https://github.com/xerial/sbt-sonatype/issues/548

**Comment by Andrapyre** [comment]
Refactoring to change to an OkHttp backend produces the following:

```
com.lumidion.sonatype.central.client.integration.test.SyncSttpItSpec *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: java/net/http/HttpTimeoutException
[info]   at sttp.client4.okhttp.OkHttpBackend.adjustExceptions(OkHttpBackend.scala:49)
[info]   at sttp.client4.okhttp.OkHttpBackend.send(OkHttpBackend.scala:38)
[info]   at sttp.client4.wrappers.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:19)
[info]   at sttp.client4.wrappers.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:15)
[info]   at sttp.client4.Request.send(request.scala:159)
[info]   at com.lumidion.sonatype.central.client.sttp.core.SyncSonatypeClient.uploadBundle(SyncSonatypeClient.scala:27)
[info]   at com.lumidion.sonatype.central.client.integration.test.SyncSttpItSpec.$anonfun$new$7(SyncSttpItSpec.scala:42)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: java.net.http.HttpTimeoutException
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
[info]   at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:103)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[info]   at sttp.client4.okhttp.OkHttpBackend.adjustExceptions(OkHttpBackend.scala:49)
[info]   at sttp.client4.okhttp.OkHttpBackend.send(OkHttpBackend.scala:38)
[info]   at sttp.client4.wrappers.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:19)
[info]   at sttp.client4.wrappers.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:15)
[info]   at sttp.client4.Request.send(request.scala:159)
[info]   at com.lumidion.sonatype.central.client.sttp.core.SyncSonatypeClient.uploadBundle(SyncSonatypeClient.scala:27)
```

**Comment by Andrapyre** [comment]
@adamw, replying to [your comment](https://github.com/xerial/sbt-sonatype/issues/548#issuecomment-2499902773), this [actions run](https://github.com/lumidion/sonatype-central-client/actions/runs/12037403480) produces the following results for Java 8:
- Scala 2.12 - `java.lang.NoClassDefFoundError: java/net/http/HttpTimeoutException`
- Scala 2.13 and 3.3.3 - `java.lang.UnsupportedClassVersionError: sttp/client4/SyncBackend has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

This is after I refactored the `HttpURLConnectionBackend` to remove any direct or downstream calls (like [this](https://github.com/softwaremill/sttp/blob/master/core/src/main/scalajvm/sttp/client4/SttpClientExceptionExtensions.scala#L20)) to classes that are Java 11+ (see[ branch](https://github.com/lumidion/sonatype-central-client/tree/fixing-backend)). 

It must be that the `httpclient` package in the sttp `core` module is forcing Java 11+ for the whole package. The `httpclient` package would probably need to be removed from `core` and put in its own module and the build machine reverted to Java 8 for when non-httpclient libs are published, if you want to support Java 8 at all, that is.

From your responses, it seems like you haven't worked with Java 8 in a while and you don't get this complaint very often (it's been years since I worked with Java 8 myself), so there is probably not enough demand to justify these breaking changes. But maybe worth putting a note in the readme that users need Java 11+ to work with sttp.

**Comment by adamw** [comment]
@Andrapyre the main documentation page (https://sttp.softwaremill.com/en/latest/) specifies that: `upported Java versions include 11+.`

**Comment by Andrapyre** [comment]
As `sbt-sonatype` no longer supports Java 8, this ticket is unnecessary. See https://github.com/xerial/sbt-sonatype/issues/530

**Comment by eed3si9n** [comment]
FYI - I'm currently lobbying to get https://github.com/xerial/sbt-sonatype/issues/530#issuecomment-2795326266 reopened since Sonatype has announced that they are sunsetting OSSRH service on June 30th, 2025. This means that library authors who publish on JDK 8 needs to figure out a way to migrate to the Central Publisher Portal.
